--- #
- name: Install required package(s)
  yum:
    name: git
    state: latest
- name: Download application installer
  get_url:
    url: "{{ installer_url }}"
    dest: /tmp/{{ installer_url | basename }}
    mode: 0555
  register: installer
- name: Generate response file for unattended install of the application
  template:
    src: "{{ app_name }}_response.varfile.j2"
    dest: /tmp/response.varfile
    mode: 0644
- name: Install application using the installer
  command: "{{ installer.dest }} -q -varfile /tmp/response.varfile"
- name: Generate and copy over bitbucket.properties for application Tomcat
  template:
    src: "{{ app_name }}.properties.j2"
    dest: "{{ home_dir }}/shared/{{ app_name }}.properties"
    mode: 0644
    force: False