apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: bitbucket
  name: bitbucket
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bitbucket
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: bitbucket
    spec:
      containers:
        - env:
            - name: SERVER_PROXY_NAME
              value: bitbucket.internal
            - name: SERVER_PROXY_PORT
              value: "80"
            - name: SERVER_SCHEME
              value: http
          image: atlassian/bitbucket:8-ubuntu-jdk17
          name: bitbucket
          volumeMounts:
            - mountPath: /var/atlassian/application-data/bitbucket
              name: bitbucket-data
      restartPolicy: Always
      volumes:
        - name: bitbucket-data
          persistentVolumeClaim:
            claimName: bitbucket-data
