apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: confluence
  name: confluence
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: confluence
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: confluence
    spec:
      containers:
        - env:
            - name: ATL_PROXY_NAME
            - name: ATL_PROXY_PORT
              value: "443"
            - name: ATL_TOMCAT_CONTEXTPATH
              value: confluence
            - name: ATL_TOMCAT_SCHEME
              value: https
            - name: ATL_TOMCAT_SECURE
              value: "false"
            - name: CERT_NAME
              value: default
            - name: VIRTUAL_HOST
            - name: VIRTUAL_PATH
              value: /confluence
            - name: VIRTUAL_PORT
              value: "8090"
          image: atlassian/confluence:8.9.5-ubuntu-jdk17
          name: confluence
          ports:
            - containerPort: 8090
              protocol: TCP
          volumeMounts:
            - mountPath: /var/atlassian/confluence
              name: confluence-data
      restartPolicy: Always
      volumes:
        - name: confluence-data
          persistentVolumeClaim:
            claimName: confluence-data
