--- #
- name: Download atlassian installers
  get_url:
    url: "{{ installer_url }}"
    dest: /tmp/{{ installer_url | basename }}
    mode: 0550
  register: installer
- name: Get response file for unattended install of the atlassian app
  template:
    src: "{{ app_name }}_response.varfile.j2"
    dest: /tmp/response.varfile
    mode: 0644
- name: Install atlassian app using the installer and response file
  command: "{{ installer.dest }} -q -varfile /tmp/response.varfile"
- name: Generate and copy over server.xml for Tomcat
  template:
    src: "{{ app_name }}_server.xml.j2"
    dest: "{{ app_dir }}/conf/server.xml"
    mode: 0644