--- #
- hosts: localhost
  become: yes
  become_method: sudo
  gather_facts: yes
  environment:
    AWS_REGION: "{{ ansible_ec2_placement_region }}"
  vars:
    db_name: bitbucket
    app_name: bitbucket
    installer_url: https://www.atlassian.com/software/stash/downloads/binary/atlassian-bitbucket-5.7.1-x64.bin
  roles:
    - setup
    - install-bitbucket
    - launch