--- #
- hosts: localhost
  become: yes
  become_method: sudo
  gather_facts: yes
  environment:
    AWS_REGION: "{{ ansible_ec2_placement_region }}"
  vars:
    db_name: jira
    app_name: jira
    installer_url: https://www.atlassian.com/software/jira/downloads/binary/atlassian-jira-software-7.7.1-x64.bin
    #installer_url: https://www.atlassian.com/software/jira/downloads/binary/atlassian-jira-core-9.12.12-x64.bin
  roles:
    - setup
    - install
    - launch